site_name: Open-CMSIS-Pack
repo_name: GitHub
repo_url: https://github.com/Open-CMSIS-Pack/landing
docs_dir: docs
nav:
  - Home: index.md
  - Resources: resources.md
theme:
  name: material
  logo: images/ARM2027_Open-CMSIS-Pack_Colour_V2.svg
  favicon: images/favicon.ico
  palette:
    scheme: default
    primary: 'white'
    accent: 'black'
markdown_extensions:
  - attr_list
  - toc:
      title: On this page
copyright: Copyright &copy; 2025 Arm Limited
extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:cmsis@arm.com
      name: Contact